# Generated by Django 6.0.5 on 2026-06-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='doenca_cronica',
            field=models.BooleanField(default=False, verbose_name='Doença crônica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hipertensao',
            field=models.BooleanField(default=False, verbose_name='Hipertensão'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da consulta'),
        ),
        migrations.CreateModel(
            name='AgendaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('BLOQUEADA', 'Bloqueada')], default='AGENDADA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['data', 'hora'],
                'unique_together': {('data', 'hora')},
            },
        ),
    ]
