# Generated by Django 6.0.5 on 2026-06-13 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_diabetes_consulta_doenca_cronica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(verbose_name='Observação / Evolução'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hipertensao',
            field=models.BooleanField(default=False, verbose_name='Hipertenso'),
        ),
        migrations.CreateModel(
            name='AuditoriaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_anterior', models.TextField(blank=True, null=True)),
                ('descricao_nova', models.TextField(blank=True, null=True)),
                ('diabetes_anterior', models.BooleanField(default=False)),
                ('diabetes_novo', models.BooleanField(default=False)),
                ('hipertensao_anterior', models.BooleanField(default=False)),
                ('hipertensao_novo', models.BooleanField(default=False)),
                ('doenca_cronica_anterior', models.BooleanField(default=False)),
                ('doenca_cronica_novo', models.BooleanField(default=False)),
                ('editado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='consultas.consulta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
