# Generated by Django 6.0.5 on 2026-06-13 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_descricao_alter_consulta_hipertensao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='consultas/fotos/')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='consultas.consulta')),
            ],
        ),
    ]
