# Generated by Django 6.0.5 on 2026-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_fotoconsulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaconsulta',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='agendaconsulta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consulta',
            name='anamnese',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='conduta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico_clinico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
