# Generated by Django 6.0.5 on 2026-06-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_agendaconsulta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação / Evolução'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico_clinico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico Clínico'),
        ),
    ]
